version: '3'

services:
  okta-sample-linux:
    container_name: okta-sample-linux-container
    build:
      context: .
      dockerfile: docker/okta-sample-linux.dockerfile
    ports:
      - "80:80"
    environment:
      OKTA_DOMAIN: dev-43780148.okta.com
      OKTA_CLIENT_ID: 0oa5uj9kwdMhBfhyV5d7
